.TH LNIX_MUNMAPFILE 3 "January 2014" lib*nix "libnix Manual"
.SH NAME
.PP
lnix_munmapFile \- unmap a file mapped into memory using lib*nix
.SH LIBRARY
.PP
lib*nix (libnix, \-lnix)
.SH SYNOPSIS
.PP
\fB\fC#include <libnix.h>\fR
.PP
\fB\fCint lnix_munmapFile\fR \fB\fC(lnix_mapFileStruct\fR *\fImapfile\fP\fB\fC);\fR
.SH DESCRIPTION
.PP
The \fB\fClnix_munmapFile\fR() function unmaps the file specified by \fImapfile\fP\&. It
should be used when a file mapped into memory by \fB\fClnix_mmapFile\fR() is no
longer needed.
.SH RETURN VALUES
.PP
If successful, \fB\fClnix_munmapFile\fR will return zero. Otherwise, it will return
a nonzero value as specified below.
.SH ERRORS
.PP
\fB\fC-1\fR
    \fB\fCmunmap\fR returned an error; check \fIerrno\fP for the specific error (\fB\fCmunmap\fR(2)).
.SH EXAMPLE
.PP
\fB\fCUnloading a mapfile after it is no longer in use.\fR
.PP
.RS
.nf
// Unload the mapfile
assert (lnix_munmapFile (&mapfile));
.fi
.RE
.SH SEE ALSO
.PP
\fB\fClnix_mremapFile\fR(3), \fB\fClnix_munmapFile\fR(3), \fB\fCmmap\fR(2), \fB\fCopen\fR(2), \fB\fCflock\fR(2), \fB\fCstat\fR(2)
.SH 
.BR AUTHOR (S)
.PP
Written for the OmniC Project \fB\fClib*nix\fR (\fB\fChttps://github.com/omnic/libnix\fR)
.PP
by Haneef Mubarak (\fB\fChttps://github.com/haneefmubarak\fR)
